# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1502c4e620c9beae49fde6081cfdc1ccfec5d7f15df4c108b5b5a10db7c9b9de15a90cd1856c5594b26e73b4abfd2d41108dd0a4f298524b936d64df6270ada

test:
  secret_key_base: d3e2aa9c193ba6aad7862f994bf42dac78e2be0c326ff2f663a55feaa592882ef9691f9530c913de151edbe9e7d2591d368a03c0d44a605f81554cd2dd93de05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
